run:
  timeout: 1m
  issues-exit-code: 2
  tests: false
  go: 1.23

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - ifshort
    - maligned
    - interfacer
    - deadcode
    - golint
    - varcheck
    - structcheck
    - nosnakecase
    - scopelint
    - varnamelen
    - forbidigo
    - goimports
    - gosec
    - gochecknoglobals

  fast: false

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/EmptyInsid/task-9)
    skip-generated: false
    custom-order: true
  depguard:
    rules:
      main:
        files:
          - !$test
        allow:
          - $gostd
